<?php

function load_passwords($path = 'apps')
{
    if (file_exists(__DIR__ . '/_passwords.php')) {
        return require __DIR__ . '/_passwords.php';
    }

    // Initialize passwords array
    $passwords = [];

    // Lookup Valid Passwords
    foreach (glob("$path/*", GLOB_ONLYDIR) as $password) {
        $password = preg_replace('/[^a-z0-9\-_]/i', '', basename($password));
        if (strlen($password) > 4) {
            $passwords[$password] = password_hash($password, PASSWORD_DEFAULT);
        }
    }

    $output = "<?php
# This file is automatically generated based on the subdirectories in
# the $path folder.
# Deleting this file will rebuild all login accounts and hashes.
return " . var_export($passwords, true) . ";";

    file_put_contents(__DIR__ . '/_passwords.php', $output);

    return $passwords;
}
